(function () {
  // Split out of weapons.js (individual weapon entries) to keep file sizes manageable.
  // See weapons.js for the merge point, WEAPONS/SKILLS export, and lookup API.
  function C(ja, zh) {
    return { ja: ja, zh: zh };
  }

  window.PriTestWeaponsData = [
    // 淑女（レディ）の初期武器。カタログに未登録だったため、他クラスの初期武器と同じ
    // 「roll: "－（初始）"」パターンで追加（技能は規則書未確認のため空、後で判明次第補記）。
    {
      id: "dagger_lady_starter",
      category: "dagger",
      name: C("レディの短剣", "淑女的短劍"),
      rarity: "C",
      roll: "－（初始）",
      skills: [],
    },
    {
      id: "dagger_lady",
      category: "dagger",
      name: C("魔力の短剣", "魔力的短劍"),
      rarity: "C",
      roll: "1〜2",
      skills: [{ kind: "innate", id: "dagger_step" }],
    },
    { id: "dagger_parrying", category: "dagger", name: C("パリングタガー", "格擋短劍"), rarity: "C", roll: "3〜4", skills: [{ kind: "innate", id: "dagger_parry" }] },
    { id: "dagger_large_knife", category: "dagger", name: C("大型ナイフ", "大型小刀"), rarity: "C", roll: "5〜6", skills: [{ kind: "status", status: C("出血", "出血") }] },
    { id: "dagger_mercy", category: "dagger", name: C("慈悲の短刀", "慈悲短刀"), rarity: "U", roll: "1", skills: [{ kind: "innate", id: "dagger_crit_up" }] },
    {
      id: "dagger_brass",
      category: "dagger",
      name: C("黄銅の短剣", "黃銅短劍"),
      rarity: "U",
      roll: "2",
      powerModOverride: C("信仰", "信仰"),
      skills: [{ kind: "random" }],
    },
    {
      id: "dagger_wakizashi",
      category: "dagger",
      name: C("脇差", "脇差"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    { id: "dagger_sickle", category: "dagger", name: C("祝祭の手鎌", "祭典鐮刀"), rarity: "U", roll: "4", skills: [{ kind: "random" }] },
    { id: "dagger_strange_knife", category: "dagger", name: C("奇晶ナイフ", "奇晶小刀"), rarity: "U", roll: "5", skills: [{ kind: "element", element: C("魔", "魔") }] },
    {
      id: "dagger_crystal_needle",
      category: "dagger",
      name: C("結晶の針", "結晶之針"),
      rarity: "U",
      roll: "6",
      powerModOverride: C("知力", "知力"),
      skills: [{ kind: "element", element: C("魔", "魔") }],
    },
    {
      id: "dagger_insect_needle",
      category: "dagger",
      name: C("蟲の針", "蟲之針"),
      rarity: "R",
      roll: "1",
      skills: [{ kind: "status", status: C("腐敗", "腐敗") }, { kind: "art", id: "art_consecutive_thrust" }],
    },
    {
      id: "dagger_cinquedea",
      category: "dagger",
      name: C("チンクエディア", "闊劍匕首"),
      rarity: "R",
      roll: "2",
      skills: [{ kind: "bonus", text: C("戦技ダメージ＋5", "戰技傷害＋5") }, { kind: "random" }],
    },
    {
      id: "dagger_glintstone_kris",
      category: "dagger",
      name: C("輝石のクリス", "輝石短劍"),
      rarity: "R",
      roll: "3",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_glintstone_shard" }],
    },
    {
      id: "dagger_reduvia",
      category: "dagger",
      name: C("レドゥビア", "雷度維亞"),
      rarity: "R",
      roll: "4",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "art", id: "art_reduvia_blood_blade" }],
    },
    {
      id: "dagger_mission_blade",
      category: "dagger",
      name: C("使命の刃", "使命之刃"),
      rarity: "R",
      roll: "5",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_golden_blade" }],
    },
    {
      id: "dagger_black_named",
      category: "dagger",
      name: C("黒名刃", "黑名刃"),
      rarity: "R",
      roll: "6",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_death_blade" }],
    },

    // ▼直剣（straightsword）
    { id: "straightsword_short_sword", category: "straightsword", name: C("ショートソード", "短劍"), rarity: "C", roll: "1", skills: [{ kind: "random" }] },
    { id: "straightsword_long_sword", category: "straightsword", name: C("ロングソード", "長劍"), rarity: "C", roll: "2〜3", skills: [{ kind: "art", id: "art_stance" }] },
    { id: "straightsword_broadsword", category: "straightsword", name: C("ブロードソード", "闊劍"), rarity: "C", roll: "4", skills: [{ kind: "random" }] },
    { id: "straightsword_worn", category: "straightsword", name: C("古びた直剣", "老舊直劍"), rarity: "C", roll: "5", skills: [{ kind: "random" }] },
    { id: "straightsword_noble_rapier", category: "straightsword", name: C("貴人の細剣", "貴人的細劍"), rarity: "C", roll: "6", skills: [{ kind: "random" }] },
    { id: "straightsword_lordsworn", category: "straightsword", name: C("君主軍の直剣", "君主軍的直劍"), rarity: "U", roll: "1", skills: [{ kind: "random" }] },
    {
      id: "straightsword_cane_sword",
      category: "straightsword",
      name: C("杖剣", "杖劍"),
      rarity: "U",
      roll: "2",
      skills: [{ kind: "innate", id: "straightsword_no_swap_cost" }],
    },
    {
      id: "straightsword_warhawk_talon",
      category: "straightsword",
      name: C("戦鷲の爪剣", "戰鷹之爪劍"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "innate", id: "straightsword_2hit_bonus" }],
    },
    {
      id: "straightsword_lazuli_glintstone",
      category: "straightsword",
      name: C("ラズリの輝石剣", "琉璃輝石劍"),
      rarity: "U",
      roll: "4",
      powerModOverride: C("知力", "知力"),
      skills: [{ kind: "element", element: C("魔", "魔") }],
    },
    {
      id: "straightsword_carian_knights",
      category: "straightsword",
      name: C("カーリアの騎士剣", "卡利亞騎士劍"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "element", element: C("魔", "魔") }],
    },
    {
      id: "straightsword_crystallized_knights",
      category: "straightsword",
      name: C("腐敗した騎士剣", "腐敗騎士劍"),
      rarity: "U",
      roll: "6",
      powerModOverride: C("知力", "知力"),
      skills: [{ kind: "status", status: C("腐敗", "腐敗") }],
    },
    {
      id: "straightsword_miquella_knights",
      category: "straightsword",
      name: C("ミケラの騎士剣", "米凱拉的騎士劍"),
      rarity: "R",
      roll: "1",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "random" }],
    },
    {
      id: "straightsword_parade",
      category: "straightsword",
      name: C("儀仗の直剣", "儀仗直劍"),
      rarity: "R",
      roll: "2",
      skills: [{ kind: "innate", id: "straightsword_dual_wield" }, { kind: "art", id: "art_golden_sword_technique" }],
    },
    {
      id: "straightsword_gravestone",
      category: "straightsword",
      name: C("黄金の墓標", "黃金的墓標"),
      rarity: "R",
      roll: "3",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "art", id: "art_mourning_tombstone" },
        { kind: "special", target: C("死に生きる者", "死而復生者") },
      ],
    },
    {
      id: "straightsword_trina",
      category: "straightsword",
      name: C("トリーナの剣", "特里娜之劍"),
      rarity: "R",
      roll: "4",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_sleeping_mist" }],
    },
    {
      id: "straightsword_eohid",
      category: "straightsword",
      name: C("エオヒドの宝剣", "艾奧希德的寶劍"),
      rarity: "R",
      roll: "5",
      powerModOverride: C("神秘", "神秘"),
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_eohid_sword_dance" }],
    },
    {
      id: "straightsword_secret_letters",
      category: "straightsword",
      name: C("秘文字の剣", "祕文字之劍"),
      rarity: "R",
      roll: "6",
      powerModOverride: C("信仰", "信仰"),
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_unyielding_blade" }],
    },
    {
      id: "straightsword_night_and_flame",
      category: "straightsword",
      name: C("夜と炎の剣", "夜與焰之劍"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "element", element: C("炎", "火") },
        { kind: "innate", id: "straightsword_night_and_flame" },
        { kind: "art", id: "art_night_and_flame_stance" },
      ],
    },

    // ▼大剣（greatsword）
    {
      id: "greatsword_pursuer",
      category: "greatsword",
      name: C("追跡者の大剣", "追跡者的大劍"),
      rarity: "C",
      roll: "－（初始）",
      skills: [{ kind: "art", id: "art_lunge" }],
    },
    { id: "greatsword_bastard_sword", category: "greatsword", name: C("バスタードソード", "混血劍"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "greatsword_iron", category: "greatsword", name: C("鉄の大剣", "鐵之大劍"), rarity: "C", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "greatsword_lordsworn", category: "greatsword", name: C("君主軍の大剣", "君主軍的大劍"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    { id: "greatsword_claymore", category: "greatsword", name: C("クレイモア", "克雷莫爾"), rarity: "U", roll: "1", skills: [{ kind: "random" }] },
    { id: "greatsword_knight", category: "greatsword", name: C("騎士大剣", "騎士大劍"), rarity: "U", roll: "2", skills: [{ kind: "innate", id: "greatsword_two_handed_bonus" }] },
    { id: "greatsword_exiled", category: "greatsword", name: C("失地騎士の大剣", "失地騎士的大劍"), rarity: "U", roll: "3", skills: [{ kind: "random" }] },
    {
      id: "greatsword_flamberge",
      category: "greatsword",
      name: C("フランベルジュ", "焰形劍"),
      rarity: "U",
      roll: "4",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    { id: "greatsword_twin_unbound", category: "greatsword", name: C("分かたれぬ双児の剣", "不可分之雙子劍"), rarity: "U", roll: "5", skills: [{ kind: "random" }] },
    { id: "greatsword_gargoyle", category: "greatsword", name: C("ガーゴイルの大剣", "石像鬼的大劍"), rarity: "U", roll: "6", skills: [{ kind: "random" }] },
    {
      id: "greatsword_gargoyle_black",
      category: "greatsword",
      name: C("ガーゴイルの黒剣", "石像鬼的黑劍"),
      rarity: "R",
      roll: "1",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_death_wax_slash" }],
    },
    {
      id: "greatsword_miyr",
      category: "greatsword",
      name: C("ミエロスの剣", "米埃洛斯之劍"),
      rarity: "R",
      roll: "2",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_miyr_scream" }],
    },
    {
      id: "greatsword_ordovis",
      category: "greatsword",
      name: C("オルドビスの大剣", "奧多維斯的大劍"),
      rarity: "R",
      roll: "3",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_ordovis_vortex" }],
    },
    {
      id: "greatsword_white_king",
      category: "greatsword",
      name: C("白王の剣", "白王之劍"),
      rarity: "R",
      roll: "4",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "art", id: "art_white_daylight_pull_wave" },
        { kind: "special", target: C("星の眷属", "星之眷屬") },
      ],
    },
    {
      id: "greatsword_death_rake",
      category: "greatsword",
      name: C("死かき棒", "死之撥棒"),
      rarity: "R",
      roll: "5",
      skills: [{ kind: "status", status: C("凍傷", "凍傷") }, { kind: "art", id: "art_frost_flame_ignition" }],
    },
    {
      id: "greatsword_helphen",
      category: "greatsword",
      name: C("ヘルフェンの尖塔", "赫爾芬的尖塔"),
      rarity: "R",
      roll: "6",
      powerModOverride: C("神秘", "神秘"),
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_ruin_spirit_flame" }],
    },
    {
      id: "greatsword_marais_executioner",
      category: "greatsword",
      name: C("マレー家の執行剣", "馬雷家的處刑劍"),
      rarity: "L",
      roll: "1",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "art", id: "art_eohid_sword_dance" },
        { kind: "innate", id: "greatsword_marais_grace" },
      ],
    },
    {
      id: "greatsword_blasphemous",
      category: "greatsword",
      name: C("冒涜の聖剣", "冒瀆的聖劍"),
      rarity: "L",
      roll: "2",
      skills: [
        { kind: "element", element: C("炎", "火") },
        { kind: "art", id: "art_plunder_flame" },
        { kind: "innate", id: "greatsword_blasphemous_grace" },
      ],
    },
    {
      id: "greatsword_golden_order",
      category: "greatsword",
      name: C("黄金律の大剣", "黃金律的大劍"),
      rarity: "L",
      roll: "3",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "status", status: C("凍傷", "凍傷") },
        { kind: "art", id: "art_golden_order_hoist" },
        { kind: "innate", id: "greatsword_golden_order_grace" },
      ],
    },
    {
      id: "greatsword_dark_moon",
      category: "greatsword",
      name: C("暗月の大剣", "闇月大劍"),
      rarity: "L",
      roll: "4",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "status", status: C("凍傷", "凍傷") },
        { kind: "art", id: "art_moonlight_blade" },
        { kind: "innate", id: "greatsword_dark_moon_grace" },
      ],
    },
    {
      id: "greatsword_marika_relic",
      category: "greatsword",
      name: C("神の遺剣", "神之遺劍"),
      rarity: "L",
      roll: "5",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "element", element: C("魔", "魔") },
        { kind: "art", id: "art_golden_wave" },
        { kind: "innate", id: "greatsword_great_grace" },
      ],
    },
    {
      id: "greatsword_l_reroll",
      category: "greatsword",
      name: C("（Lで出目⑥）", "（L出目⑥）"),
      rarity: "L",
      roll: "6",
      skills: [{ kind: "note", text: C("Lで再抽選する。", "重新抽選L稀有度。") }],
    },

    { id: "colossal_zweihander", category: "colossal", name: C("ツヴァイヘンダー", "雙手巨劍"), rarity: "C", roll: "1〜3", skills: [{ kind: "random" }] },
    { id: "colossal_greatsword", category: "colossal", name: C("グレートソード", "大劍"), rarity: "C", roll: "4〜6", skills: [{ kind: "random" }] },
    { id: "colossal_thunder_hound", category: "colossal", name: C("番犬の大剣", "番犬的大劍"), rarity: "U", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "colossal_troll_golden", category: "colossal", name: C("トロルの黄金剣", "巨魔的黃金劍"), rarity: "U", roll: "3〜4", skills: [{ kind: "random" }] },
    {
      id: "colossal_troll_knight",
      category: "colossal",
      name: C("トロルの騎士剣", "巨魔的騎士劍"),
      rarity: "U",
      roll: "5〜6",
      skills: [{ kind: "element", element: C("魔", "魔") }],
    },
    {
      id: "colossal_royal_greatsword",
      category: "colossal",
      name: C("王家のグレートソード", "王家的大劍"),
      rarity: "R",
      roll: "1〜3",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_wolf_assault" }],
    },
    {
      id: "colossal_godslayer",
      category: "colossal",
      name: C("神狩りの剣", "狩神之劍"),
      rarity: "R",
      roll: "4〜6",
      skills: [{ kind: "element", element: C("炎", "火") }, { kind: "art", id: "art_queens_black_flame" }],
    },
    {
      id: "colossal_flensing",
      category: "colossal",
      name: C("剣接ぎの大剣", "接劍的大劍"),
      rarity: "L",
      roll: "1",
      skills: [
        { kind: "innate", id: "colossal_vengeance_grace" },
        { kind: "art", id: "colossal_vow_of_vengeance" },
      ],
    },
    {
      id: "colossal_ruins",
      category: "colossal",
      name: C("遺跡の大剣", "遺跡的大劍"),
      rarity: "L",
      roll: "2",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "innate", id: "colossal_collapse_grace" },
        { kind: "art", id: "colossal_collapse_wave" },
      ],
    },
    {
      id: "colossal_starcrusher",
      category: "colossal",
      name: C("星砕きの大剣", "碎星的大劍"),
      rarity: "L",
      roll: "3",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "innate", id: "colossal_starcrusher_grace" },
        { kind: "art", id: "colossal_star_call" },
      ],
    },
    {
      id: "colossal_marikes_black",
      category: "colossal",
      name: C("マリケスの黒き剣", "馬利卡斯的黑劍"),
      rarity: "L",
      roll: "4",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "innate", id: "colossal_fate_of_death_grace" },
        { kind: "art", id: "colossal_fate_of_death" },
      ],
    },
    {
      id: "colossal_l_reroll",
      category: "colossal",
      name: C("（Lで出目⑤〜⑥）", "（L出目⑤〜⑥）"),
      rarity: "L",
      roll: "5〜6",
      skills: [{ kind: "note", text: C("Lで再抽選する。", "重新抽選L稀有度。") }],
    },

    // ▼刺剣（rapier）／重刺剣（heavy_rapier）
    { id: "rapier_scholar", category: "rapier", name: C("学者の剃剣", "學者的剃劍"), rarity: "C", roll: "－（初始）", skills: [{ kind: "art", id: "art_consecutive_thrust" }] },
    { id: "rapier_rapier", category: "rapier", name: C("レイピア", "西洋劍"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "rapier_estoc", category: "rapier", name: C("エストック", "刺劍"), rarity: "C", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "rapier_noble_estoc", category: "rapier", name: C("貴人のエストック", "貴人的埃斯托克"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    { id: "rapier_noble_knight", category: "rapier", name: C("貴腐騎士の剣", "貴腐騎士的劍"), rarity: "U", roll: "1〜3", skills: [{ kind: "random" }] },
    {
      id: "rapier_rogier",
      category: "rapier",
      name: C("ロジェールのレイピア", "羅傑爾的西洋劍"),
      rarity: "U",
      roll: "4〜6",
      skills: [{ kind: "random" }],
    },
    {
      id: "rapier_ant_thread",
      category: "rapier",
      name: C("蟻棘のレイピア", "蟻棘的西洋劍"),
      rarity: "R",
      roll: "1〜3",
      skills: [{ kind: "status", status: C("腐敗", "腐敗") }, { kind: "random" }],
    },
    {
      id: "rapier_ice_needle",
      category: "rapier",
      name: C("氷結の針", "冰結之針"),
      rarity: "R",
      roll: "4〜6",
      skills: [{ kind: "status", status: C("凍傷", "凍傷") }, { kind: "random" }],
    },
    {
      id: "rapier_none_l",
      category: "rapier",
      name: C("（L表には該当武器なし）", "（L稀有度無對應武器）"),
      rarity: "L",
      roll: "－",
      skills: [{ kind: "note", text: C("この表には存在しない。Rの表で再抽選する。", "此稀有度不存在此武器，改於R表重新抽選。") }],
    },

    { id: "heavy_rapier_great_eva", category: "heavy_rapier", name: C("グレート・エバ", "偉大・伊娃"), rarity: "C", roll: "1〜6", skills: [{ kind: "art", id: "art_piercing_thrust" }] },
    { id: "heavy_rapier_god_skin_stitcher", category: "heavy_rapier", name: C("神肌繍い", "神肌縫合"), rarity: "U", roll: "1〜6", skills: [{ kind: "random" }] },
    {
      id: "heavy_rapier_bloody_helice",
      category: "heavy_rapier",
      name: C("血のヘリケー", "血之螺旋"),
      rarity: "R",
      roll: "1〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "innate", id: "heavy_rapier_dynasty_art" }],
    },
    {
      id: "heavy_rapier_dragon_king",
      category: "heavy_rapier",
      name: C("竜王の岩剣", "龍王的岩劍"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "element", element: C("雷", "雷") },
        { kind: "innate", id: "heavy_rapier_thunderclad" },
        { kind: "innate", id: "heavy_rapier_dragon_grace" },
        { kind: "special", target: C("竜", "龍") },
      ],
    },

    // ▼曲剣（curved_sword）／大曲剣（great_curved_sword）
    { id: "curved_sword_scimitar", category: "curved_sword", name: C("シミター", "彎刀"), rarity: "C", roll: "1〜2", skills: [{ kind: "art", id: "art_vacuum_slash" }] },
    { id: "curved_sword_falchion", category: "curved_sword", name: C("ファルシオン", "彎背刀"), rarity: "C", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "curved_sword_shotel", category: "curved_sword", name: C("ショーテル", "肖特爾"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "curved_sword_shamshir",
      category: "curved_sword",
      name: C("シャムシール", "彎月刀"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "innate", id: "curved_sword_2hit_bonus" }],
    },
    { id: "curved_sword_grossmesser", category: "curved_sword", name: C("グロスメッサー", "大砍刀"), rarity: "U", roll: "2", skills: [{ kind: "random" }] },
    { id: "curved_sword_corpse_piler", category: "curved_sword", name: C("死体漁りの曲刀", "拾屍者的彎刀"), rarity: "U", roll: "3", skills: [{ kind: "random" }] },
    {
      id: "curved_sword_ant_sting",
      category: "curved_sword",
      name: C("蟻螫り", "蟻螫"),
      rarity: "U",
      roll: "4",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "curved_sword_beastman",
      category: "curved_sword",
      name: C("獣人の曲刀", "獸人的彎刀"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "innate", id: "curved_sword_power_mod_up" }, { kind: "innate", id: "curved_sword_heal_up" }],
    },
    {
      id: "curved_sword_serpent_god",
      category: "curved_sword",
      name: C("蛇神の曲刀", "蛇神的彎刀"),
      rarity: "U",
      roll: "6",
      skills: [{ kind: "innate", id: "curved_sword_power_mod_up" }, { kind: "random" }],
    },
    {
      id: "curved_sword_flowing_water",
      category: "curved_sword",
      name: C("流水の曲刀", "流水的彎刀"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "element", element: C("炎", "火") }, { kind: "art", id: "art_lava_scatter" }],
    },
    {
      id: "curved_sword_magma_blade",
      category: "curved_sword",
      name: C("溶岩刀", "熔岩刀"),
      rarity: "R",
      roll: "3",
      skills: [{ kind: "innate", id: "curved_sword_power_mod_up" }, { kind: "art", id: "art_fluidization" }],
    },
    {
      id: "curved_sword_nox_fluid",
      category: "curved_sword",
      name: C("ノクスの流体剣", "諾克斯流體劍"),
      rarity: "R",
      roll: "4〜5",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "art", id: "art_nebula" },
        { kind: "special", target: C("星の眷属", "星之眷屬") },
      ],
    },
    {
      id: "curved_sword_astel_fin",
      category: "curved_sword",
      name: C("アステールの海羽", "亞絲緹爾的海翼"),
      rarity: "R",
      roll: "6",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "art", id: "art_death_flare" },
        { kind: "innate", id: "curved_sword_despair_grace" },
      ],
    },
    {
      id: "curved_sword_eclipse_shotel",
      category: "curved_sword",
      name: C("蝕のショーテル", "蝕之肖特爾"),
      rarity: "L",
      roll: "1〜6",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_death_flare" }],
    },

    { id: "great_curved_sword_zanbato", category: "great_curved_sword", name: C("斬馬刀", "斬馬刀"), rarity: "C", roll: "1〜6", skills: [{ kind: "random" }] },
    {
      id: "great_curved_sword_omen",
      category: "great_curved_sword",
      name: C("忌み子の大刀", "忌子的大刀"),
      rarity: "U",
      roll: "1〜2",
      skills: [{ kind: "random" }],
    },
    { id: "great_curved_sword_monk_flame", category: "great_curved_sword", name: C("僧兵の炎姿刀", "僧兵炎姿刀"), rarity: "U", roll: "3", skills: [{ kind: "random" }] },
    { id: "great_curved_sword_beastman", category: "great_curved_sword", name: C("獣人の大曲刀", "獸人大曲刀"), rarity: "U", roll: "4〜5", skills: [{ kind: "random" }] },
    {
      id: "great_curved_sword_hound_fang",
      category: "great_curved_sword",
      name: C("猟犬の長牙", "獵犬的長牙"),
      rarity: "U",
      roll: "6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "innate", id: "great_curved_sword_hound_volley" }],
    },
    {
      id: "great_curved_sword_black_knight",
      category: "great_curved_sword",
      name: C("黒王の大剣", "黑王的大劍"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "innate", id: "great_curved_sword_black_king_repel" }],
    },
    {
      id: "great_curved_sword_zamiel",
      category: "great_curved_sword",
      name: C("ザミエルの海刃", "扎米爾的海刃"),
      rarity: "R",
      roll: "3〜4",
      skills: [{ kind: "status", status: C("凍傷", "凍傷") }, { kind: "art", id: "art_zamiel_ice_storm" }],
    },
    {
      id: "great_curved_sword_earth_dragon",
      category: "great_curved_sword",
      name: C("土竜の鱗剣", "土龍的鱗刃"),
      rarity: "R",
      roll: "5〜6",
      skills: [{ kind: "element", element: C("炎", "火") }, { kind: "innate", id: "great_curved_sword_lava_guillotine" }],
    },
    {
      id: "great_curved_sword_morgott",
      category: "great_curved_sword",
      name: C("モーゴットの呪剣", "莫格的咒劍"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "great_curved_sword_cursed_blood_slash" },
        { kind: "innate", id: "great_curved_sword_king_of_woe_grace" },
      ],
    },

    // ▼刀（katana）
    {
      id: "katana_executioner",
      category: "katana",
      name: C("執行者の刀", "執行者的刀"),
      rarity: "C",
      roll: "－",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "art", id: "art_iai" }],
    },
    {
      id: "katana_uchigatana",
      category: "katana",
      name: C("打刀", "打刀"),
      rarity: "C",
      roll: "1〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "katana_fang",
      category: "katana",
      name: C("長牙", "長牙"),
      rarity: "U",
      roll: "1〜2",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "katana_serpent_belt",
      category: "katana",
      name: C("蛇腹の刀", "蛇腹之刀"),
      rarity: "U",
      roll: "3〜4",
      skills: [{ kind: "status", status: C("猛毒", "猛毒") }, { kind: "random" }],
    },
    {
      id: "katana_meteor",
      category: "katana",
      name: C("隕鉄の刀", "隕鐵之刀"),
      rarity: "U",
      roll: "5〜6",
      skills: [
        { kind: "status", status: C("出血", "出血") },
        { kind: "random" },
        { kind: "special", target: C("星の眷属", "星之眷屬") },
      ],
    },
    {
      id: "katana_moon_veil",
      category: "katana",
      name: C("名刀月隠", "名刀月隱"),
      rarity: "R",
      roll: "1〜2",
      skills: [
        { kind: "innate", id: "katana_power_up5" },
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "katana_moment_of_moonlight" },
      ],
    },
    {
      id: "katana_corpse_pile",
      category: "katana",
      name: C("屍山河", "屍山河"),
      rarity: "R",
      roll: "3〜4",
      skills: [
        { kind: "innate", id: "katana_power_up5" },
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "katana_countless_corpses" },
      ],
    },
    {
      id: "katana_dragon_scale",
      category: "katana",
      name: C("竜鱗刀", "龍鱗刀"),
      rarity: "R",
      roll: "5〜6",
      skills: [{ kind: "innate", id: "katana_power_up10" }, { kind: "innate", id: "katana_ice_thunder_kill" }],
    },
    {
      id: "katana_malenia_prosthesis",
      category: "katana",
      name: C("マレニアの義手刀", "馬蓮妮亞的義手刀"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "katana_water_bird_dance" },
        { kind: "innate", id: "katana_unbroken_grace" },
      ],
    },

    // ▼両刃剣（twinblade）
    { id: "twinblade_twinblade", category: "twinblade", name: C("ツインブレード", "雙刃劍"), rarity: "C", roll: "1〜6", skills: [{ kind: "random" }] },
    { id: "twinblade_twin_knight_sword", category: "twinblade", name: C("ツインナイトソード", "雙子騎士劍"), rarity: "U", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "twinblade_god_skin_peeler", category: "twinblade", name: C("神肌剥ぎ", "神肌剝離"), rarity: "U", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "twinblade_gargoyle", category: "twinblade", name: C("ガーゴイルの両刃", "石像鬼的雙刃"), rarity: "U", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "twinblade_gargoyle_black",
      category: "twinblade",
      name: C("ガーゴイルの黒両刃", "石像鬼的黑雙刃"),
      rarity: "R",
      roll: "1〜3",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "status", status: C("凍傷", "凍傷") },
        { kind: "art", id: "art_bloody_blade_dance" },
      ],
    },
    {
      id: "twinblade_eleonora",
      category: "twinblade",
      name: C("エレオノーラの双刃", "艾蕾諾拉的雙刃"),
      rarity: "R",
      roll: "4〜6",
      skills: [
        { kind: "innate", id: "twinblade_power_down5" },
        { kind: "element", element: C("炎", "火") },
        { kind: "status", status: C("出血", "出血") },
        { kind: "art", id: "art_bloody_blade_dance" },
      ],
    },
    {
      id: "twinblade_none_l",
      category: "twinblade",
      name: C("（L表には該当武器なし）", "（L稀有度無對應武器）"),
      rarity: "L",
      roll: "－",
      skills: [{ kind: "note", text: C("この表には存在しない。Rの表で再抽選する。", "此稀有度不存在此武器，改於R表重新抽選。") }],
    },

    // ▼槌（mace）／斧（axe）
    {
      id: "mace_funeral",
      category: "mace",
      name: C("葬儀屋の槌", "殯葬者的槌"),
      rarity: "C",
      roll: "－",
      skills: [{ kind: "art", id: "art_prayer_strike" }],
    },
    { id: "mace_club", category: "mace", name: C("クラブ", "棍棒"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "mace_bent_stick", category: "mace", name: C("曲り棍棒", "彎曲棍棒"), rarity: "C", roll: "3", skills: [{ kind: "random" }] },
    { id: "mace_stone_club", category: "mace", name: C("石棍棒", "石棍棒"), rarity: "C", roll: "4", skills: [{ kind: "random" }] },
    { id: "mace_mace", category: "mace", name: C("メイス", "狼牙棒"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "mace_fanged",
      category: "mace",
      name: C("牙付き棍棒", "尖牙棍棒"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    {
      id: "mace_morning_star",
      category: "mace",
      name: C("モーニングスター", "晨星錘"),
      rarity: "U",
      roll: "2",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    {
      id: "mace_warpick",
      category: "mace",
      name: C("ウォーピック", "戰鎬"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "random" }],
    },
    { id: "mace_hammer", category: "mace", name: C("ハンマー", "鐵鎚"), rarity: "U", roll: "4", skills: [{ kind: "random" }] },
    { id: "mace_monk_flame", category: "mace", name: C("僧兵の炎姿槌", "僧兵的炎姿槌"), rarity: "U", roll: "5", skills: [{ kind: "random" }] },
    {
      id: "mace_varre",
      category: "mace",
      name: C("ヴァレーの花束", "瓦雷的花束"),
      rarity: "U",
      roll: "6",
      powerModOverride: C("神秘", "神秘"),
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    {
      id: "mace_messenger_flute",
      category: "mace",
      name: C("使者たちの笛", "使者們的笛"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "innate", id: "mace_oracle_bubble" }],
    },
    {
      id: "mace_nox_flowing",
      category: "mace",
      name: C("ノクスの流体槌", "諾克斯的流體槌"),
      rarity: "R",
      roll: "3〜4",
      skills: [{ kind: "innate", id: "mace_two_handed_bonus" }, { kind: "innate", id: "mace_fluidize" }],
    },
    {
      id: "mace_ring_finger",
      category: "mace",
      name: C("指輪指", "指環指"),
      rarity: "R",
      roll: "5",
      skills: [{ kind: "innate", id: "mace_power_up5" }, { kind: "innate", id: "mace_flick" }],
    },
    {
      id: "mace_hyakuchi_staff",
      category: "mace",
      name: C("百智の王笏", "百智的王笏"),
      rarity: "R",
      roll: "6",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "innate", id: "mace_hyakuchi_world" }],
    },
    {
      id: "mace_marika",
      category: "mace",
      name: C("マリカの槌", "瑪莉卡的槌"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "innate", id: "mace_golden_crush" },
        { kind: "innate", id: "mace_queens_protection" },
      ],
    },

    { id: "axe_hand_axe", category: "axe", name: C("ハンドアクス", "手斧"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "axe_forked", category: "axe", name: C("二又の手斧", "分岔手斧"), rarity: "C", roll: "3", skills: [{ kind: "random" }] },
    { id: "axe_battle_axe", category: "axe", name: C("バトルアクス", "戰斧"), rarity: "C", roll: "4", skills: [{ kind: "random" }] },
    { id: "axe_toothed", category: "axe", name: C("歯列の斧", "齒列之斧"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "axe_warped",
      category: "axe",
      name: C("歪んだ斧", "扭曲之斧"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "innate", id: "axe_two_handed_bonus" }],
    },
    { id: "axe_iron_hatchet", category: "axe", name: C("鉄の鉈", "鐵鉈"), rarity: "U", roll: "2〜3", skills: [{ kind: "random" }] },
    { id: "axe_highland", category: "axe", name: C("ハイランドアクス", "高地斧"), rarity: "U", roll: "4", skills: [{ kind: "random" }] },
    { id: "axe_festival_hatchet", category: "axe", name: C("祝祭の鉈", "祝祭之鉈"), rarity: "U", roll: "5", skills: [{ kind: "random" }] },
    {
      id: "axe_ripple_sword",
      category: "axe",
      name: C("波紋の剣", "波紋之劍"),
      rarity: "U",
      roll: "6",
      powerModOverride: C("神秘", "神秘"),
      skills: [{ kind: "random" }],
    },
    {
      id: "axe_ice_calamity",
      category: "axe",
      name: C("氷殻の斧", "冰殼之斧"),
      rarity: "R",
      roll: "1",
      skills: [
        { kind: "status", status: C("凍傷", "凍傷") },
        { kind: "special", target: C("竜", "龍") },
      ],
    },
    {
      id: "axe_sacrifice",
      category: "axe",
      name: C("生贄の斧", "祭品之斧"),
      rarity: "R",
      roll: "2〜3",
      skills: [{ kind: "innate", id: "axe_two_handed_bonus" }, { kind: "random" }],
    },
    {
      id: "axe_storm_hawk",
      category: "axe",
      name: C("嵐鷹の斧", "嵐鷹之斧"),
      rarity: "R",
      roll: "4",
      skills: [{ kind: "innate", id: "axe_two_handed_bonus" }, { kind: "innate", id: "axe_thunder_storm" }],
    },
    {
      id: "axe_roses",
      category: "axe",
      name: C("ローゼスの斧", "羅葉之斧"),
      rarity: "R",
      roll: "5〜6",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_roses_call" }],
    },
    {
      id: "axe_none_l",
      category: "axe",
      name: C("（L表には該当武器なし）", "（L稀有度無對應武器）"),
      rarity: "L",
      roll: "－",
      skills: [{ kind: "note", text: C("この表には存在しない。Rの表で再抽選する。", "此稀有度不存在此武器，改於R表重新抽選。") }],
    },

    // ▼フレイル（flail）
    {
      id: "flail_flail",
      category: "flail",
      name: C("フレイル", "連枷"),
      rarity: "C",
      roll: "1〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "innate", id: "flail_chain_swing" }],
    },
    {
      id: "flail_night_cavalry",
      category: "flail",
      name: C("夜騎兵のフレイル", "夜騎兵的連枷"),
      rarity: "U",
      roll: "1〜3",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "innate", id: "flail_chain_swing" }],
    },
    {
      id: "flail_linked_mace",
      category: "flail",
      name: C("連接棍", "連接棍"),
      rarity: "U",
      roll: "4〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "innate", id: "flail_chain_swing" }],
    },
    {
      id: "flail_family_head",
      category: "flail",
      name: C("家族の首", "家族之首"),
      rarity: "R",
      roll: "1〜6",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "innate", id: "flail_family_wail" }],
    },
    {
      id: "flail_fallen_star_child",
      category: "flail",
      name: C("落とし子の星々", "棄子的群星"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "innate", id: "flail_stardust" },
        { kind: "special", target: C("星の眷属", "星之眷屬") },
        { kind: "innate", id: "flail_dark_grace" },
      ],
    },

    // ▼大槌（greatmace）
    { id: "greatmace_large_club", category: "greatmace", name: C("ラージクラブ", "大棍棒"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "greatmace_bent_greatclub", category: "greatmace", name: C("曲り大棍棒", "彎曲大棍棒"), rarity: "C", roll: "3", skills: [{ kind: "random" }] },
    {
      id: "greatmace_great_mace",
      category: "greatmace",
      name: C("グレートメイス", "大狼牙棒"),
      rarity: "C",
      roll: "4",
      skills: [{ kind: "innate", id: "greatmace_two_handed_bonus" }],
    },
    { id: "greatmace_pickaxe", category: "greatmace", name: C("つるはし", "十字鎬"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "greatmace_cairn_hammer",
      category: "greatmace",
      name: C("積石の槌", "積石之槌"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "innate", id: "greatmace_two_handed_bonus" }],
    },
    { id: "greatmace_battle_hammer", category: "greatmace", name: C("バトルハンマー", "戰鎚"), rarity: "U", roll: "2", skills: [{ kind: "random" }] },
    {
      id: "greatmace_rotten_battle_hammer",
      category: "greatmace",
      name: C("腐敗したバトルハンマー", "腐敗的戰鎚"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "status", status: C("腐敗", "腐敗") }],
    },
    { id: "greatmace_festival_greatskull", category: "greatmace", name: C("祝祭の大頭蓋", "祝祭的大頭蓋"), rarity: "U", roll: "4", skills: [{ kind: "random" }] },
    {
      id: "greatmace_great_stars",
      category: "greatmace",
      name: C("グレートスターズ", "巨星錘"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    { id: "greatmace_great_horn_hammer", category: "greatmace", name: C("大角の槌", "大角之槌"), rarity: "U", roll: "6", skills: [{ kind: "random" }] },
    {
      id: "greatmace_long_flute",
      category: "greatmace",
      name: C("使者たちの長笛", "使者們的長笛"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "innate", id: "greatmace_bubble_shower" }],
    },
    {
      id: "greatmace_venerable_candlestand",
      category: "greatmace",
      name: C("尊顔の燭台", "尊顏的燭台"),
      rarity: "R",
      roll: "3〜4",
      skills: [{ kind: "element", element: C("炎", "火") }, { kind: "innate", id: "greatmace_erupting_faith" }],
    },
    {
      id: "greatmace_beast_claw",
      category: "greatmace",
      name: C("獣爪の大槌", "獸爪之大槌"),
      rarity: "R",
      roll: "5〜6",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "innate", id: "greatmace_beast_king_claw" }],
    },
    {
      id: "greatmace_world_eater_scepter",
      category: "greatmace",
      name: C("世界喰らいの王笏", "吞噬世界的王笏"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "element", element: C("炎", "火") },
        { kind: "innate", id: "greatmace_world_eater" },
        { kind: "innate", id: "greatmace_desecration_grace" },
      ],
    },

    // ▼大斧（greataxe）
    { id: "greataxe_greataxe", category: "greataxe", name: C("グレートアクス", "大斧"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "greataxe_crescent_axe", category: "greataxe", name: C("三日月斧", "新月斧"), rarity: "C", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "greataxe_long_hilt", category: "greataxe", name: C("長柄鉈", "長柄鉈"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "greataxe_torso_cleave",
      category: "greataxe",
      name: C("断胴の大鉈", "斷胴的大鉈"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "innate", id: "greataxe_crit_up20" }],
    },
    {
      id: "greataxe_omen_crush",
      category: "greataxe",
      name: C("忌み潰しの大鉈", "忌子壓碎的大鉈"),
      rarity: "U",
      roll: "2",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    { id: "greataxe_rusted_anchor", category: "greataxe", name: C("錆び付いた錨", "生鏽的錨"), rarity: "U", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "greataxe_gargoyle", category: "greataxe", name: C("ガーゴイルの大斧", "石像鬼的大斧"), rarity: "U", roll: "5〜6", skills: [{ kind: "random" }] },
    {
      id: "greataxe_gargoyle_black",
      category: "greataxe",
      name: C("ガーゴイルの黒斧", "石像鬼的黑斧"),
      rarity: "R",
      roll: "1〜3",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "random" }],
    },
    { id: "greataxe_dismantling_cleaver", category: "greataxe", name: C("解体包丁", "解體包丁"), rarity: "R", roll: "4〜6", skills: [{ kind: "random" }] },
    {
      id: "greataxe_winged_horn",
      category: "greataxe",
      name: C("翼の大角", "翼之大角"),
      rarity: "L",
      roll: "1〜3",
      skills: [
        { kind: "innate", id: "greataxe_two_handed_bonus" },
        { kind: "innate", id: "greataxe_ghost_affliction_call" },
      ],
    },
    {
      id: "greataxe_godrick",
      category: "greataxe",
      name: C("ゴドリックの王斧", "戈德里克的王斧"),
      rarity: "L",
      roll: "4〜6",
      skills: [
        { kind: "innate", id: "greataxe_kneel_before_me" },
        { kind: "innate", id: "greataxe_golden_lineage_grace" },
      ],
    },

    // ▼特大武器（great_weapon）
    { id: "great_weapon_ruffian", category: "great_weapon", name: C("無頼漢の大斧", "無賴漢的大斧"), rarity: "C", roll: "－", skills: [{ kind: "art", id: "art_endure" }] },
    { id: "great_weapon_gladiator", category: "great_weapon", name: C("闘士の大斧", "鬥士的大斧"), rarity: "C", roll: "1〜6", skills: [{ kind: "random" }] },
    {
      id: "great_weapon_rotten",
      category: "great_weapon",
      name: C("腐敗した大斧", "腐敗的大斧"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "status", status: C("腐敗", "腐敗") }],
    },
    { id: "great_weapon_golem_axe_spear", category: "great_weapon", name: C("ゴーレムの斧槍", "傀儡的斧槍"), rarity: "U", roll: "2", skills: [{ kind: "random" }] },
    { id: "great_weapon_giant_crusher", category: "great_weapon", name: C("巨人砕き", "巨人碎"), rarity: "U", roll: "3〜4", skills: [{ kind: "random" }] },
    {
      id: "great_weapon_great_club",
      category: "great_weapon",
      name: C("グレートクラブ", "巨棍"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "element", element: C("聖", "聖") }],
    },
    {
      id: "great_weapon_troll_hammer",
      category: "great_weapon",
      name: C("トロルハンマー", "巨魔鎚"),
      rarity: "U",
      roll: "6",
      skills: [{ kind: "element", element: C("炎", "火") }],
    },
    {
      id: "great_weapon_great_dragon_claw",
      category: "great_weapon",
      name: C("大竜爪", "大龍爪"),
      rarity: "R",
      roll: "1",
      skills: [
        { kind: "element", element: C("雷", "雷") },
        { kind: "random" },
        { kind: "special", target: C("竜", "龍") },
      ],
    },
    {
      id: "great_weapon_watchdog_staff",
      category: "great_weapon",
      name: C("番犬の錫杖", "番犬的錫杖"),
      rarity: "R",
      roll: "2",
      skills: [
        { kind: "innate", id: "great_weapon_two_handed_bonus" },
        { kind: "innate", id: "great_weapon_pilgrims_staff_magic" },
      ],
    },
    {
      id: "great_weapon_rotten_duty",
      category: "great_weapon",
      name: C("腐敗した儀仗", "腐敗的儀仗"),
      rarity: "R",
      roll: "3",
      skills: [
        { kind: "status", status: C("腐敗", "腐敗") },
        { kind: "innate", id: "great_weapon_golden_tree_slam" },
      ],
    },
    {
      id: "great_weapon_messenger_fan_flute",
      category: "great_weapon",
      name: C("使者たちの扇笛", "使者們的扇笛"),
      rarity: "R",
      roll: "4",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "innate", id: "great_weapon_oracle_great_bubble" },
      ],
    },
    {
      id: "great_weapon_geezers_wheel",
      category: "great_weapon",
      name: C("ギーザの車輪", "老者的車輪"),
      rarity: "R",
      roll: "5",
      skills: [
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "great_weapon_wheel_spin" },
      ],
    },
    {
      id: "great_weapon_star_beast_jaw",
      category: "great_weapon",
      name: C("星獣の顎", "星獸之顎"),
      rarity: "R",
      roll: "6",
      skills: [
        { kind: "element", element: C("魔", "魔") },
        { kind: "innate", id: "great_weapon_gravity_thunder" },
        { kind: "special", target: C("星の眷属", "星之眷屬") },
      ],
    },
    {
      id: "great_weapon_godfrey",
      category: "great_weapon",
      name: C("ゴッドフレイの王斧", "戈弗雷的王斧"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "innate", id: "great_weapon_kings_roar" },
        { kind: "innate", id: "great_weapon_first_king_grace" },
      ],
    },

    // ▼槍（spear）／大槍（great_spear）
    { id: "spear_short_spear", category: "spear", name: C("ショートスピア", "短矛"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "spear_iron", category: "spear", name: C("鉄の槍", "鐵之槍"), rarity: "C", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "spear_spear", category: "spear", name: C("スピア", "長矛"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    { id: "spear_partisan", category: "spear", name: C("パルチザン", "戟矛"), rarity: "U", roll: "1", skills: [{ kind: "random" }] },
    {
      id: "spear_pike",
      category: "spear",
      name: C("パイク", "長槍"),
      rarity: "U",
      roll: "2",
      skills: [{ kind: "innate", id: "spear_backline_attack" }],
    },
    {
      id: "spear_cross_glaive",
      category: "spear",
      name: C("十文字薙刀", "十字薙刀"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    {
      id: "spear_clay_man",
      category: "spear",
      name: C("泥人の銛", "泥人的魚叉"),
      rarity: "U",
      roll: "4",
      skills: [{ kind: "element", element: C("魔", "魔") }],
    },
    {
      id: "spear_vulgar_militia",
      category: "spear",
      name: C("ポールトーチ", "火把矛"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "element", element: C("炎", "火") }],
    },
    {
      id: "spear_corrupted_crystal",
      category: "spear",
      name: C("腐敗した結晶槍", "腐敗的結晶槍"),
      rarity: "U",
      roll: "6",
      skills: [{ kind: "status", status: C("腐敗", "腐敗") }],
    },
    {
      id: "spear_inquisitors_candlestand",
      category: "spear",
      name: C("責問燭台", "審問燭台"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "spear_noble_knight",
      category: "spear",
      name: C("貴腐騎士の槍", "貴腐騎士的槍"),
      rarity: "R",
      roll: "3〜4",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_ancient_spear" }],
    },
    {
      id: "spear_death_ritual",
      category: "spear",
      name: C("死儀礼の槍", "死儀禮之槍"),
      rarity: "R",
      roll: "5〜6",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "art", id: "art_piercing_spear" }],
    },
    {
      id: "spear_granskaxe_thunder",
      category: "spear",
      name: C("グランサクスの雷", "格蘭薩克斯的雷"),
      rarity: "L",
      roll: "1〜6",
      skills: [{ kind: "element", element: C("雷", "雷") }, { kind: "art", id: "art_blood_draw_spear" }],
    },

    { id: "great_spear_lance", category: "great_spear", name: C("ランス", "騎槍"), rarity: "C", roll: "1〜6", skills: [{ kind: "art", id: "art_charge" }] },
    { id: "great_spear_tree", category: "great_spear", name: C("ツリースピア", "樹矛"), rarity: "U", roll: "1〜3", skills: [{ kind: "element", element: C("雷", "雷") }] },
    {
      id: "great_spear_serpent_hunter",
      category: "great_spear",
      name: C("大蛇狩り", "獵大蛇者"),
      rarity: "U",
      roll: "4〜6",
      skills: [{ kind: "innate", id: "great_spear_serpent_hunt" }],
    },
    {
      id: "great_spear_ciriria",
      category: "great_spear",
      name: C("シルリアの樹槍", "西琉里亞的樹槍"),
      rarity: "R",
      roll: "1〜3",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "innate", id: "great_spear_ciriria_vortex" }],
    },
    {
      id: "great_spear_vyke",
      category: "great_spear",
      name: C("ヴァイクの戦槍", "維克的戰槍"),
      rarity: "R",
      roll: "4〜6",
      skills: [
        { kind: "element", element: C("炎", "火") },
        { kind: "status", status: C("発狂", "發狂") },
        { kind: "innate", id: "great_spear_mad_flame_thrust" },
      ],
    },
    {
      id: "great_spear_mohgwyn",
      category: "great_spear",
      name: C("モーグウィンの聖槍", "莫格温的聖槍"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "element", element: C("炎", "火") },
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "great_spear_blood_gifting_rite" },
        { kind: "innate", id: "great_spear_blood_lord_grace" },
      ],
    },

    // ▼斧槍（halberd）
    { id: "halberd_guardian", category: "halberd", name: C("守護者の斧槍", "守護者的斧槍"), rarity: "C", roll: "－", skills: [{ kind: "art", id: "art_charge" }] },
    { id: "halberd_halberd", category: "halberd", name: C("ハルバード", "戟槍"), rarity: "C", roll: "1", skills: [{ kind: "random" }] },
    { id: "halberd_exiled_knight", category: "halberd", name: C("失地騎士の斧槍", "失地騎士的斧槍"), rarity: "C", roll: "2", skills: [{ kind: "random" }] },
    { id: "halberd_lutzeern", category: "halberd", name: C("ルッツエルン", "盧策倫"), rarity: "C", roll: "3", skills: [{ kind: "random" }] },
    { id: "halberd_glaive", category: "halberd", name: C("グレイブ", "偃月刀"), rarity: "C", roll: "4", skills: [{ kind: "random" }] },
    { id: "halberd_low_shotel", category: "halberd", name: C("卑兵のショーテル", "卑兵的肖特爾"), rarity: "C", roll: "5", skills: [{ kind: "random" }] },
    { id: "halberd_low_saw", category: "halberd", name: C("卑兵のノコギリ", "卑兵的鋸子"), rarity: "C", roll: "6", skills: [{ kind: "status", status: C("出血", "出血") }] },
    {
      id: "halberd_guardsman_spear",
      category: "halberd",
      name: C("守人の剣槍", "守人的劍槍"),
      rarity: "U",
      roll: "1",
      powerModOverride: C("技量", "技量"),
      skills: [{ kind: "random" }],
    },
    { id: "halberd_night_cavalry_glaive", category: "halberd", name: C("夜騎兵のグレイブ", "夜騎兵的偃月刀"), rarity: "U", roll: "2", skills: [{ kind: "random" }] },
    { id: "halberd_insect_glaive", category: "halberd", name: C("蟲のグレイブ", "蟲之偃月刀"), rarity: "U", roll: "3", skills: [{ kind: "random" }] },
    {
      id: "halberd_thunder_gap",
      category: "halberd",
      name: C("欠波紋の斧槍", "欠波紋的斧槍"),
      rarity: "U",
      roll: "4〜5",
      powerModOverride: C("神秘", "神秘"),
      skills: [{ kind: "random" }],
    },
    { id: "halberd_gargoyle", category: "halberd", name: C("ガーゴイルの斧槍", "石像鬼的斧槍"), rarity: "U", roll: "6", skills: [{ kind: "random" }] },
    {
      id: "halberd_gargoyle_black",
      category: "halberd",
      name: C("ガーゴイルの黒斧槍", "石像鬼的黑斧槍"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "element", element: C("雷", "雷") }, { kind: "random" }],
    },
    {
      id: "halberd_golden_halberd",
      category: "halberd",
      name: C("黄金のハルバード", "黃金戟槍"),
      rarity: "R",
      roll: "3",
      skills: [{ kind: "innate", id: "halberd_two_handed_bonus" }, { kind: "random" }],
    },
    {
      id: "halberd_dragon",
      category: "halberd",
      name: C("竜のハルバード", "龍之戟槍"),
      rarity: "R",
      roll: "4",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "random" }],
    },
    {
      id: "halberd_loretta",
      category: "halberd",
      name: C("ローレッタの戦鎌", "羅蕾塔的戰鐮"),
      rarity: "R",
      roll: "5",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "random" }],
    },
    {
      id: "halberd_veteran_banner",
      category: "halberd",
      name: C("宿将の軍旗", "宿將的軍旗"),
      rarity: "R",
      roll: "6",
      skills: [
        { kind: "innate", id: "halberd_two_handed_bonus" },
        { kind: "innate", id: "halberd_under_the_banner" },
      ],
    },
    {
      id: "halberd_none_l",
      category: "halberd",
      name: C("（L表には該当武器なし）", "（L稀有度無對應武器）"),
      rarity: "L",
      roll: "－",
      skills: [{ kind: "note", text: C("この表には存在しない。Rの表で再抽選する。", "此稀有度不存在此武器，改於R表重新抽選。") }],
    },

    // ▼鎌（scythe）
    {
      id: "scythe_greatscythe",
      category: "scythe",
      name: C("大鎌", "大鐮"),
      rarity: "C",
      roll: "1〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "scythe_grave",
      category: "scythe",
      name: C("墓場の大鎌", "墓場的大鐮"),
      rarity: "U",
      roll: "1〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "scythe_halo_scythe",
      category: "scythe",
      name: C("光輪のサイス", "光輪的鐮刀"),
      rarity: "R",
      roll: "1〜3",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "scythe_miquella_halo" },
      ],
    },
    {
      id: "scythe_wing",
      category: "scythe",
      name: C("翼の鎌", "翼之鐮"),
      rarity: "R",
      roll: "4〜6",
      skills: [
        { kind: "element", element: C("聖", "聖") },
        { kind: "status", status: C("出血", "出血") },
        { kind: "innate", id: "scythe_angel_wing" },
      ],
    },
    {
      id: "scythe_none_l",
      category: "scythe",
      name: C("（L表には該当武器なし）", "（L稀有度無對應武器）"),
      rarity: "L",
      roll: "－",
      skills: [{ kind: "note", text: C("この表には存在しない。Rの表で再抽選する。", "此稀有度不存在此武器，改於R表重新抽選。") }],
    },

    // ▼鞭（whip）
    { id: "whip_whip", category: "whip", name: C("ウィップ", "鞭"), rarity: "C", roll: "1〜6", skills: [{ kind: "random" }] },
    {
      id: "whip_thorn",
      category: "whip",
      name: C("茨鞭", "荊棘鞭"),
      rarity: "U",
      roll: "1〜3",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    {
      id: "whip_urumi",
      category: "whip",
      name: C("ウルミ", "烏魯米"),
      rarity: "U",
      roll: "4〜6",
      skills: [{ kind: "random" }],
    },
    {
      id: "whip_hoslow",
      category: "whip",
      name: C("ホスローの花弁", "霍斯洛的花瓣"),
      rarity: "R",
      roll: "1〜3",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "whip_lava_candlestand",
      category: "whip",
      name: C("溶岩鞭の燭台", "熔岩鞭之燭台"),
      rarity: "R",
      roll: "4〜6",
      skills: [{ kind: "element", element: C("炎", "火") }, { kind: "innate", id: "whip_lava_sea" }],
    },
    {
      id: "whip_giant_redhair",
      category: "whip",
      name: C("巨人の赤髪", "巨人的赤髮"),
      rarity: "L",
      roll: "1〜6",
      skills: [{ kind: "element", element: C("炎", "火") }, { kind: "innate", id: "whip_flame_dance" }],
    },

    // ▼拳（fist）
    {
      id: "fist_vengeful",
      category: "fist",
      name: C("復讐者の呪爪", "復仇者的咒爪"),
      rarity: "C",
      roll: "－",
      powerModOverride: C("信仰", "信仰"),
      skills: [{ kind: "art", id: "art_white_shadow_invite" }],
    },
    { id: "fist_katar", category: "fist", name: C("カタール", "卡塔爾"), rarity: "C", roll: "1〜3", skills: [{ kind: "random" }] },
    { id: "fist_cestus", category: "fist", name: C("セスタス", "凱斯特斯"), rarity: "C", roll: "4〜6", skills: [{ kind: "random" }] },
    {
      id: "fist_spike_cestus",
      category: "fist",
      name: C("スパイクセスタス", "尖刺凱斯特斯"),
      rarity: "U",
      roll: "1〜2",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    { id: "fist_iron_ball", category: "fist", name: C("鉄球拳", "鐵球拳"), rarity: "U", roll: "3〜4", skills: [{ kind: "random" }] },
    {
      id: "fist_spiked_ball",
      category: "fist",
      name: C("棘球拳", "棘球拳"),
      rarity: "U",
      roll: "5〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }],
    },
    {
      id: "fist_clinging_bone",
      category: "fist",
      name: C("縋り付く手骨", "纏附的手骨"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "innate", id: "fist_life_reaping_fist" }],
    },
    {
      id: "fist_veteran_leg",
      category: "fist",
      name: C("宿将の義足", "宿將的義肢"),
      rarity: "R",
      roll: "3〜4",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "innate", id: "fist_storm_kick" }],
    },
    {
      id: "fist_secret_letters_pata",
      category: "fist",
      name: C("秘文字のパタ", "祕文字的帕塔"),
      rarity: "R",
      roll: "5〜6",
      powerModOverride: C("信仰", "信仰"),
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_unyielding_blade" }],
    },
    {
      id: "fist_spliced_wyrm",
      category: "fist",
      name: C("接がれた飛竜", "接合的飛龍"),
      rarity: "L",
      roll: "1〜6",
      skills: [
        { kind: "innate", id: "fist_dragon_grace" },
        { kind: "element", element: C("炎", "火") },
        { kind: "innate", id: "fist_behold" },
      ],
    },

    // ▼爪（claw）
    {
      id: "claw_hooked",
      category: "claw",
      name: C("鉤爪", "鉤爪"),
      rarity: "C",
      roll: "1〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "claw_hound",
      category: "claw",
      name: C("猟犬の爪", "獵犬之爪"),
      rarity: "U",
      roll: "1〜3",
      skills: [{ kind: "status", status: C("毒", "毒") }, { kind: "random" }],
    },
    {
      id: "claw_viper_fang",
      category: "claw",
      name: C("毒蛇の牙", "毒蛇之牙"),
      rarity: "U",
      roll: "4〜6",
      skills: [{ kind: "status", status: C("出血", "出血") }, { kind: "random" }],
    },
    {
      id: "claw_raptor_talon",
      category: "claw",
      name: C("猛禽の鉤爪", "猛禽之鉤爪"),
      rarity: "R",
      roll: "1〜6",
      skills: [{ kind: "random" }],
    },
    {
      id: "claw_none_l",
      category: "claw",
      name: C("（L表には該当武器なし）", "（L稀有度無對應武器）"),
      rarity: "L",
      roll: "－",
      skills: [{ kind: "note", text: C("この表には存在しない。Rの表で再抽選する。", "此稀有度不存在此武器，改於R表重新抽選。") }],
    },

    // ▼弓（bow）：種類決定表の写真により、C～Rの構成を修正（旧データはランク・出目・一部名称が不正確だった）。
    { id: "bow_iron_eye", category: "bow", name: C("鉄の目の弓", "鐵目之弓"), rarity: "C", roll: "－", skills: [{ kind: "art", id: "art_strong_shot" }] },
    { id: "bow_shortbow", category: "bow", name: C("ショートボウ", "短弓"), rarity: "C", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "bow_hybrid_short", category: "bow", name: C("混種の小弓", "混種短弓"), rarity: "C", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "bow_longbow", category: "bow", name: C("ロングボウ", "長弓"), rarity: "C", roll: "5〜6", skills: [{ kind: "random" }] },
    { id: "bow_composite", category: "bow", name: C("コンポジットボウ", "複合弓"), rarity: "U", roll: "1", skills: [{ kind: "random" }] },
    { id: "bow_redwood_short", category: "bow", name: C("赤木のショートボウ", "赤木短弓"), rarity: "U", roll: "2", skills: [{ kind: "random" }] },
    { id: "bow_harp", category: "bow", name: C("ハープボウ", "豎琴弓"), rarity: "U", roll: "3", skills: [{ kind: "random" }] },
    { id: "bow_silver", category: "bow", name: C("しろがねの弓", "白銀弓"), rarity: "U", roll: "4", skills: [{ kind: "random" }] },
    { id: "bow_horn", category: "bow", name: C("角の弓", "角弓"), rarity: "U", roll: "5", skills: [{ kind: "random" }] },
    { id: "bow_black", category: "bow", name: C("黒弓", "黑弓"), rarity: "R", roll: "1〜2", skills: [{ kind: "random" }] },
    { id: "bow_pulley", category: "bow", name: C("滑車の弓", "滑輪弓"), rarity: "R", roll: "3〜4", skills: [{ kind: "random" }] },
    { id: "bow_serpent", category: "bow", name: C("蛇弓", "蛇弓"), rarity: "R", roll: "5", skills: [{ kind: "status", status: C("猛毒", "猛毒") }] },
    { id: "bow_erdtree", category: "bow", name: C("黄金樹の弓", "黃金樹之弓"), rarity: "R", roll: "6", skills: [{ kind: "element", element: C("聖", "聖") }] },

    // ▼大弓（greatbow）
    { id: "greatbow_greatbow", category: "greatbow", name: C("大弓", "大弓"), rarity: "C", roll: "－", skills: [{ kind: "art", id: "art_piercing_shot" }] },
    {
      id: "greatbow_golem",
      category: "greatbow",
      name: C("ゴーレムの大弓", "傀儡的大弓"),
      rarity: "U",
      roll: "－",
      skills: [{ kind: "art", id: "art_piercing_shot" }],
    },
    {
      id: "greatbow_erdtree",
      category: "greatbow",
      name: C("黄金樹の大弓", "黃金樹的大弓"),
      rarity: "R",
      roll: "－",
      skills: [{ kind: "element", element: C("聖", "聖") }, { kind: "art", id: "art_piercing_shot" }],
    },
    {
      id: "greatbow_lion",
      category: "greatbow",
      name: C("獅子の大弓", "獅子的大弓"),
      rarity: "L",
      roll: "－",
      skills: [
        { kind: "innate", id: "greatbow_general_grace" },
        { kind: "innate", id: "greatbow_radahn_downpour" },
      ],
    },

    // ▼クロスボウ（crossbow）：種類決定表の写真により、出目範囲とレア度（クレプスの黒鐔／月輪の弩／滑車の弩）を修正。
    { id: "crossbow_soldier", category: "crossbow", name: C("兵士のクロスボウ", "士兵的弩"), rarity: "C", roll: "1〜2", skills: [{ kind: "innate", id: "crossbow_kick" }] },
    { id: "crossbow_light", category: "crossbow", name: C("ライトクロスボウ", "輕弩"), rarity: "C", roll: "3〜4", skills: [{ kind: "innate", id: "crossbow_kick" }] },
    { id: "crossbow_heavy", category: "crossbow", name: C("ヘビークロスボウ", "重弩"), rarity: "C", roll: "5", skills: [{ kind: "innate", id: "crossbow_kick" }] },
    { id: "crossbow_arbalest", category: "crossbow", name: C("アーバレスト", "十字弩"), rarity: "C", roll: "6", skills: [{ kind: "innate", id: "crossbow_kick" }] },
    { id: "crossbow_kreps", category: "crossbow", name: C("クレプスの黒鐔", "克雷普斯的黑鐔"), rarity: "U", roll: "1〜3", skills: [{ kind: "innate", id: "crossbow_kick" }] },
    {
      id: "crossbow_moon_ring",
      category: "crossbow",
      name: C("月輪の弩", "月輪之弩"),
      rarity: "U",
      roll: "4〜6",
      skills: [{ kind: "element", element: C("魔", "魔") }, { kind: "innate", id: "crossbow_kick" }],
    },
    {
      id: "crossbow_pulley",
      category: "crossbow",
      name: C("滑車の弩", "滑車之弩"),
      rarity: "R",
      roll: "1〜6",
      skills: [{ kind: "innate", id: "crossbow_kick" }, { kind: "note", text: C("武器威力40＋▲（他のクロスボウと異なる特殊な基礎値）", "武器威力40＋▲（與其他弩不同的特殊基礎值）") }],
    },

    // ▼バリスタ（ballista）：種類決定表の写真により、装備品スキルは「なし」に修正（従来のキック付与は誤り）。
    { id: "ballista_handheld", category: "ballista", name: C("手持ちバリスタ", "手持式弩砲"), rarity: "U", roll: "－", skills: [] },
    { id: "ballista_pot_cannon", category: "ballista", name: C("壺大砲", "壺大砲"), rarity: "R", roll: "－", skills: [] },

    // ▼盾（shield）：種類決定表の写真により全面的に再構成（2026年7月訂正）。
    // attachedEffect＝付随効果／reverseArt＝逆手の戦技（ガード時戦技）。「蓄積無効｜X」「ガード時蓄積｜X」はnote扱い。
    {
      id: "small_shield_pursuer",
      category: "small_shield",
      name: C("追跡者の小盾", "追跡者的小盾"),
      rarity: "C",
      roll: "－",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "innate", id: "small_shield_reverse_parry" }],
    },
    {
      id: "small_shield_iron_bowl",
      category: "small_shield",
      name: C("鉄鉢の木盾", "鐵缽木盾"),
      rarity: "C",
      roll: "1",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "note", text: C("逆手の戦技ダメージ＋10", "反手戰技傷害＋10") }],
    },
    {
      id: "small_shield_pale_blue",
      category: "small_shield",
      name: C("青白の木盾", "青白的木盾"),
      rarity: "C",
      roll: "2",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_scripture",
      category: "small_shield",
      name: C("聖句の木盾", "聖句木盾"),
      rarity: "C",
      roll: "3",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_red_thorn",
      category: "small_shield",
      name: C("赤茨の木盾", "赤茨木盾"),
      rarity: "C",
      roll: "4",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_pillory",
      category: "small_shield",
      name: C("首枷の盾", "首枷盾"),
      rarity: "C",
      roll: "5",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "note", text: C("蓄積無効｜呪死", "蓄積無效｜咒死") }],
    },
    {
      id: "small_shield_buckler",
      category: "small_shield",
      name: C("バックラー", "巴克勒盾"),
      rarity: "C",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "innate", id: "small_shield_reverse_parry" }],
    },
    {
      id: "small_shield_iron_round",
      category: "small_shield",
      name: C("鉄の円盾", "鐵圓盾"),
      rarity: "U",
      roll: "1〜2",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_gilded_iron",
      category: "small_shield",
      name: C("金装の鉄盾", "金裝鐵盾"),
      rarity: "U",
      roll: "3",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜聖", "蓄積無效｜聖") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_snake",
      category: "small_shield",
      name: C("蛇人の盾", "蛇人之盾"),
      rarity: "U",
      roll: "4",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜炎", "蓄積無效｜炎") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_frost_iron",
      category: "small_shield",
      name: C("氷紋の鉄盾", "冰紋鐵盾"),
      rarity: "U",
      roll: "5",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜魔", "蓄積無效｜魔") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_crevice",
      category: "small_shield",
      name: C("裂け目の盾", "裂縫之盾"),
      rarity: "U",
      roll: "6",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜発狂", "蓄積無效｜發狂") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_incense",
      category: "small_shield",
      name: C("調香師の盾", "調香師之盾"),
      rarity: "R",
      roll: "1",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_sinner",
      category: "small_shield",
      name: C("咎人の盾", "咎人之盾"),
      rarity: "R",
      roll: "2〜3",
      attachedEffect: [{ kind: "note", text: C("ガード時蓄積｜出血", "防禦時蓄積｜出血") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_horn_whirl",
      category: "small_shield",
      name: C("角渦の盾", "角渦之盾"),
      rarity: "R",
      roll: "4",
      attachedEffect: [{ kind: "note", text: C("ガード時蓄積｜出血", "防禦時蓄積｜出血") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_smoldering",
      category: "small_shield",
      name: C("燻りの盾", "燻之盾"),
      rarity: "R",
      roll: "5",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜炎", "蓄積無效｜炎") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "small_shield_coiled",
      category: "small_shield",
      name: C("蜷局の盾", "蜷局之盾"),
      rarity: "R",
      roll: "6",
      attachedEffect: [{ kind: "note", text: C("ガード時蓄積｜猛毒", "防禦時蓄積｜猛毒") }],
      reverseArt: [{ kind: "innate", id: "small_shield_poison_bite" }],
    },

    {
      id: "medium_shield_hawk",
      category: "medium_shield",
      name: C("鷹紋のウッドシールド", "鷹紋木盾"),
      rarity: "C",
      roll: "1",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_flame_crest",
      category: "medium_shield",
      name: C("炎紋のウッドシールド", "炎紋木盾"),
      rarity: "C",
      roll: "2",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_round",
      category: "medium_shield",
      name: C("ラウンドシールド", "圓盾"),
      rarity: "C",
      roll: "3",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_eaten_leather",
      category: "medium_shield",
      name: C("蝕まれた革盾", "蝕蝕皮盾"),
      rarity: "C",
      roll: "4",
      attachedEffect: [{ kind: "note", text: C("ガード時蓄積｜出血", "防禦時蓄積｜出血") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_heater",
      category: "medium_shield",
      name: C("ヒーターシールド", "熱盾"),
      rarity: "C",
      roll: "5",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_eaten_heater",
      category: "medium_shield",
      name: C("蝕紋のヒーターシールド", "蝕紋熱盾"),
      rarity: "C",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_capital_of_sun",
      category: "medium_shield",
      name: C("太陽の都の盾", "太陽都之盾"),
      rarity: "U",
      roll: "1",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_large_leather",
      category: "medium_shield",
      name: C("ラージレザーシールド", "大皮盾"),
      rarity: "U",
      roll: "2",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_black_leather",
      category: "medium_shield",
      name: C("ブラックレザーシールド", "黑皮盾"),
      rarity: "U",
      roll: "3",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜凍傷", "蓄積無效｜凍傷") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_kite",
      category: "medium_shield",
      name: C("カイトシールド", "風箏盾"),
      rarity: "U",
      roll: "4",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_locust_kite",
      category: "medium_shield",
      name: C("蝗のカイトシールド", "蝗蟲風箏盾"),
      rarity: "U",
      roll: "5",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_twin_bird_kite",
      category: "medium_shield",
      name: C("双鳥のカイトシールド", "雙鳥風箏盾"),
      rarity: "U",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_brass",
      category: "medium_shield",
      name: C("真鍮の盾", "黃銅盾"),
      rarity: "R",
      roll: "1",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_silver_bird",
      category: "medium_shield",
      name: C("しろがねの盾", "白銀盾"),
      rarity: "R",
      roll: "2",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜魔", "蓄積無效｜魔") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_beast_man",
      category: "medium_shield",
      name: C("獣人の壺盾", "獸人壺盾"),
      rarity: "R",
      roll: "3",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_carian_knight",
      category: "medium_shield",
      name: C("カーリアの騎士盾", "卡利亞的騎士盾"),
      rarity: "R",
      roll: "4",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜聖", "蓄積無效｜聖") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_silver",
      category: "medium_shield",
      name: C("白銀の盾", "白銀之盾"),
      rarity: "R",
      roll: "5",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜魔", "蓄積無效｜魔") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "medium_shield_turtle",
      category: "medium_shield",
      name: C("大亀の甲羅", "大龜的龜殼"),
      rarity: "R",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },

    {
      id: "large_shield_guardian",
      category: "large_shield",
      name: C("守護者の大盾", "守護者的大盾"),
      rarity: "C",
      roll: "－",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "note", text: C("逆手の戦技ダメージ＋5", "反手戰技傷害＋5") }],
    },
    {
      id: "large_shield_wood",
      category: "large_shield",
      name: C("木の大盾", "木製大盾"),
      rarity: "C",
      roll: "1",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_lords_army",
      category: "large_shield",
      name: C("君主軍の大盾", "君主軍大盾"),
      rarity: "C",
      roll: "2",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_manor_tower",
      category: "large_shield",
      name: C("城館のタワーシールド", "城館塔盾"),
      rarity: "C",
      roll: "3",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_crossed_tree_tower",
      category: "large_shield",
      name: C("交差樹のタワーシールド", "交叉樹塔盾"),
      rarity: "C",
      roll: "4",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_inverted_hawk_tower",
      category: "large_shield",
      name: C("逆さ鷹のタワーシールド", "倒鷹塔盾"),
      rarity: "C",
      roll: "5",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_dragon_tower",
      category: "large_shield",
      name: C("龍のタワーシールド", "龍之塔盾"),
      rarity: "C",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_iron_thorn",
      category: "large_shield",
      name: C("鉄茨の大盾", "鐵茨的大盾"),
      rarity: "U",
      roll: "1",
      attachedEffect: [{ kind: "note", text: C("ガード時蓄積｜出血", "防禦時蓄積｜出血") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_sawtooth",
      category: "large_shield",
      name: C("鋸壁の盾", "鋸壁盾"),
      rarity: "U",
      roll: "2",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "note", text: C("逆手の戦技ダメージ＋10", "反手戰技傷害＋10") }],
    },
    {
      id: "large_shield_sacred_painting",
      category: "large_shield",
      name: C("神聖画の盾", "聖畫盾"),
      rarity: "U",
      roll: "3",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_gold",
      category: "large_shield",
      name: C("黄金の大盾", "黃金大盾"),
      rarity: "U",
      roll: "4",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_holy_tree",
      category: "large_shield",
      name: C("聖樹紋の大盾", "聖樹紋大盾"),
      rarity: "U",
      roll: "5",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜聖", "蓄積無效｜聖") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_eaten_crest",
      category: "large_shield",
      name: C("蝕紋の大盾", "蝕紋大盾"),
      rarity: "U",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_dragon_claw",
      category: "large_shield",
      name: C("龍爪の盾", "龍爪盾"),
      rarity: "R",
      roll: "1",
      attachedEffect: [{ kind: "note", text: C("蓄積無効｜雷", "蓄積無效｜雷") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_fingerprint",
      category: "large_shield",
      name: C("指紋石の盾", "指紋石盾"),
      rarity: "R",
      roll: "2",
      attachedEffect: [{ kind: "note", text: C("ガード時蓄積｜発狂", "防禦時蓄積｜發狂") }],
      reverseArt: [{ kind: "random" }],
    },
    {
      id: "large_shield_golden_tree",
      category: "large_shield",
      name: C("黄金樹の大盾", "黃金樹的大盾"),
      rarity: "R",
      roll: "3",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "innate", id: "large_shield_golden_retribution" }],
    },
    {
      id: "large_shield_jellyfish",
      category: "large_shield",
      name: C("クラゲの盾", "水母盾"),
      rarity: "R",
      roll: "4",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "innate", id: "large_shield_contagious_fury" }],
    },
    {
      id: "large_shield_ganmen",
      category: "large_shield",
      name: C("ガンメンの盾", "顏面盾"),
      rarity: "R",
      roll: "5",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "innate", id: "large_shield_flame_belch" }],
    },
    {
      id: "large_shield_single_eye",
      category: "large_shield",
      name: C("単眼の盾", "單眼之盾"),
      rarity: "R",
      roll: "6",
      attachedEffect: [{ kind: "random" }],
      reverseArt: [{ kind: "innate", id: "large_shield_flame_spit" }],
    },

    // ▼杖（staff）：種類決定表・固有魔術ページを撮影再確認して全17種を収録（2026年7月訂正）。
    // 装備品スキル欄は魔術（spell_*）を参照する。※ランダム魔術（A/B表）は random 扱い。
    {
      id: "staff_hermit",
      category: "staff",
      name: C("隠者の杖", "隱者的杖"),
      rarity: "C",
      roll: "－",
      skills: [{ kind: "art", id: "spell_glintstone_pebble" }, { kind: "art", id: "spell_glintstone_arc" }],
    },
    {
      id: "staff_stargazer",
      category: "staff",
      name: C("星見の杖", "觀星的杖"),
      rarity: "C",
      roll: "1〜2",
      skills: [{ kind: "art", id: "spell_glintstone_pebble" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_glintstone",
      category: "staff",
      name: C("輝石の杖", "輝石之杖"),
      rarity: "C",
      roll: "3",
      skills: [{ kind: "art", id: "spell_glintstone_pebble" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_academy",
      category: "staff",
      name: C("学院の輝石杖", "學院的輝石杖"),
      rarity: "C",
      roll: "4",
      skills: [{ kind: "art", id: "spell_glintstone_pebble" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_demihuman_queen",
      category: "staff",
      name: C("亜人女王の杖", "亞人女王的杖"),
      rarity: "C",
      roll: "5",
      skills: [{ kind: "art", id: "spell_glintstone_pebble" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_meteorite",
      category: "staff",
      name: C("石掘り杖", "拾石者的杖"),
      rarity: "C",
      roll: "6",
      skills: [{ kind: "art", id: "spell_rock_sling" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_carian_glintstone",
      category: "staff",
      name: C("カーリアの輝石杖", "卡利亞的輝石杖"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "art", id: "spell_carian_slicer" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_carian_glintblade",
      category: "staff",
      name: C("カーリアの輝剣杖", "卡利亞的輝劍杖"),
      rarity: "U",
      roll: "2",
      skills: [{ kind: "art", id: "spell_royal_carian_glintblade" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_loss",
      category: "staff",
      name: C("喪失の杖", "喪失之杖"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "art", id: "spell_night_comet" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_gelmir_glintstone",
      category: "staff",
      name: C("ゲルミアの輝石杖", "格爾米爾的輝石杖"),
      rarity: "U",
      roll: "4",
      skills: [{ kind: "art", id: "spell_lava_bolt" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_crystal",
      category: "staff",
      name: C("結晶杖", "結晶杖"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "art", id: "spell_shattering_crystal" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_sinner",
      category: "staff",
      name: C("咎人の杖", "咎人之杖"),
      rarity: "U",
      roll: "6",
      skills: [{ kind: "art", id: "spell_thorns_of_punishment" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_azur_glintstone",
      category: "staff",
      name: C("アズールの輝石杖", "阿祖爾的輝石杖"),
      rarity: "R",
      roll: "1〜2",
      skills: [{ kind: "art", id: "spell_azur_comet" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_lusat_glintstone",
      category: "staff",
      name: C("ルーサットの輝石杖", "盧薩特的輝石杖"),
      rarity: "R",
      roll: "3〜4",
      skills: [{ kind: "art", id: "spell_ruinous_meteor" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_meteor",
      category: "staff",
      name: C("隕石の杖", "隕石之杖"),
      rarity: "R",
      roll: "5",
      skills: [{ kind: "art", id: "spell_gravity_bolt" }, { kind: "random", table: "A" }],
    },
    {
      id: "staff_death_prince",
      category: "staff",
      name: C("死王子の杖", "死亡王子的杖"),
      rarity: "R",
      roll: "6",
      skills: [{ kind: "art", id: "spell_ghost_call" }, { kind: "random", table: "B" }],
    },
    {
      id: "staff_carian_regal_scepter",
      category: "staff",
      name: C("カーリアの正笏", "卡利亞的正笏"),
      rarity: "L",
      roll: "1〜6",
      skills: [{ kind: "art", id: "spell_rennalas_full_moon" }, { kind: "random", table: "A" }],
    },

    // ▼聖印（sacred_seal）：種類決定表・固有祈祷ページを撮影再確認して全15種を収録（2026年7月訂正）。
    // Lレアリティは規則書上「存在しない（Rの表で再抽選する）」と明記されているため未収録。
    {
      id: "seal_finger_start",
      category: "sacred_seal",
      name: C("指の聖印（復讐者初期装備）", "手指的聖印（復仇者初期裝備）"),
      rarity: "C",
      roll: "－",
      skills: [{ kind: "art", id: "prayer_rejection" }, { kind: "art", id: "prayer_heal" }],
    },
    {
      id: "seal_finger_a",
      category: "sacred_seal",
      name: C("指の聖印", "手指的聖印"),
      rarity: "C",
      roll: "1〜3",
      skills: [{ kind: "art", id: "prayer_rejection" }, { kind: "random", table: "A" }],
    },
    {
      id: "seal_finger_b",
      category: "sacred_seal",
      name: C("指の聖印", "手指的聖印"),
      rarity: "C",
      roll: "4〜6",
      skills: [{ kind: "art", id: "prayer_rejection" }, { kind: "random", table: "B" }],
    },
    {
      id: "seal_pebble_a",
      category: "sacred_seal",
      name: C("さざれ石の聖印", "碎石的聖印"),
      rarity: "U",
      roll: "1",
      skills: [{ kind: "art", id: "prayer_lightning_spear" }, { kind: "random", table: "A" }],
    },
    {
      id: "seal_pebble_b",
      category: "sacred_seal",
      name: C("さざれ石の聖印", "碎石的聖印"),
      rarity: "U",
      roll: "2",
      skills: [{ kind: "art", id: "prayer_lightning_spear" }, { kind: "random", table: "B" }],
    },
    {
      id: "seal_giant_a",
      category: "sacred_seal",
      name: C("巨人の聖印", "巨人的聖印"),
      rarity: "U",
      roll: "3",
      skills: [{ kind: "art", id: "prayer_firebomb" }, { kind: "random", table: "A" }],
    },
    {
      id: "seal_giant_c",
      category: "sacred_seal",
      name: C("巨人の聖印", "巨人的聖印"),
      rarity: "U",
      roll: "4",
      skills: [{ kind: "art", id: "prayer_firebomb" }, { kind: "random", table: "C" }],
    },
    {
      id: "seal_godslayer",
      category: "sacred_seal",
      name: C("神狩りの聖印", "狩神的聖印"),
      rarity: "U",
      roll: "5",
      skills: [{ kind: "art", id: "prayer_black_flame" }, { kind: "random", table: "B" }],
    },
    {
      id: "seal_claw_mark",
      category: "sacred_seal",
      name: C("爪痕の聖印", "爪痕的聖印"),
      rarity: "U",
      roll: "6",
      skills: [{ kind: "art", id: "prayer_beast_stone" }, { kind: "random", table: "A" }],
    },
    {
      id: "seal_erdtree_a",
      category: "sacred_seal",
      name: C("黄金樹の聖印", "黃金樹的聖印"),
      rarity: "R",
      roll: "1",
      skills: [{ kind: "art", id: "prayer_golden_fury" }, { kind: "random", table: "A" }],
    },
    {
      id: "seal_erdtree_b",
      category: "sacred_seal",
      name: C("黄金樹の聖印", "黃金樹的聖印"),
      rarity: "R",
      roll: "2",
      skills: [{ kind: "art", id: "prayer_golden_fury" }, { kind: "random", table: "B" }],
    },
    {
      id: "seal_golden_order_b",
      category: "sacred_seal",
      name: C("黄金律の聖印", "黃金律的聖印"),
      rarity: "R",
      roll: "3",
      skills: [{ kind: "art", id: "prayer_golden_order_fundamentalism_halo" }, { kind: "random", table: "B" }],
    },
    {
      id: "seal_golden_order_c",
      category: "sacred_seal",
      name: C("黄金律の聖印", "黃金律的聖印"),
      rarity: "R",
      roll: "4",
      skills: [{ kind: "art", id: "prayer_golden_order_fundamentalism_halo" }, { kind: "random", table: "C" }],
    },
    {
      id: "seal_frenzied_flame",
      category: "sacred_seal",
      name: C("狂い火の聖印", "狂火的聖印"),
      rarity: "R",
      roll: "5",
      skills: [{ kind: "art", id: "prayer_frenzied_flame" }, { kind: "random", table: "B" }],
    },
    {
      id: "seal_dragon_communion",
      category: "sacred_seal",
      name: C("竜餐の印", "龍餐的印"),
      rarity: "R",
      roll: "6",
      skills: [{ kind: "art", id: "prayer_dragon_feast" }, { kind: "random", table: "A" }],
    },
  ];
})();
